### ISSUE TITLE
Missing S3 permissions for 0.7.0

### ISSUE THREAD

**Issue by jhermann21** [binxio/cfn-ses-provider#14]
Good stuff. I just hit a snag with 0.7.0. When I deploy cfn-resource-provider in the CFNSESProvider resource with:

`S3Key: !If
          - UsePublicLambda
          - lambdas/cfn-ses-provider-0.7.0.zip`

I get the following error: 
Your access has been denied by S3, please make sure your request credentials have permission to GetObject for binxio-public-us-west-2/lambdas/cfn-ses-provider-0.7.0.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 6da6066e-5f87-431b-9abe-8e42c3c5151a; Proxy: null)

But if I run

`S3Key: !If
          - UsePublicLambda
          - lambdas/cfn-ses-provider-0.6.1.zip`

The stack successfully deploys.

**Comment by mvanholsteijn** [comment]
sorry. I updated the bucket policy to be public read. It works now.

curl https://binxio-public-us-west-2.s3.us-west-2.amazonaws.com/lambdas/cfn-ses-provider-0.7.0.zip -o /dev/null
