### ISSUE TITLE
Encrypted SNS topics not supported by 

### ISSUE THREAD

**Issue by couchgott** [binxio/cfn-ses-provider#16]
Heyho,

when i am using something like: 

  XXXXSESIdentityNotifications:
    Type: Custom::IdentityNotifications
    Properties:
      Identity: !GetAtt XXXXSESVerifiedIdentity.Identity
      Region: !GetAtt XXXXSESVerifiedIdentity.Region
      BounceTopic: !Ref XXXXNotificationTopic
      ComplaintTopic: !Ref  XXXXNotificationTopic
      HeadersInBounceNotificationsEnabled: true
      HeadersInComplaintNotificationsEnabled: true
      ForwardingEnabled: false
      ServiceToken: !Ref XXXXSESProviderArn

In my cloudformation template usually it works. exept i use an encrypted SNS topioc for Bount/Complaint Topic like:

  XXXXNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId: alias/aws/sns
      Subscription:
      - Endpoint:
          Ref: XXXXOperatorEMail
        Protocol: email

then i get an Error:

Received response status [FAILED] from custom resource. Message returned: botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the SetIdentityNotificationTopic operation: SNS topic arn:aws:sns:eu-central-1:XXXXXXX:XXXXXX... (RequestId: XXXXXXX )

tested with version 0.6.5 as well as 0.7.0
Any idea? :)

**Comment by mvanholsteijn** [comment]
Are the SNS Topic and the SES Email Identity in the same region? Otherwise you may be looking at a misleading error message from boto3. https://github.com/boto/boto3/issues/2645

**Comment by couchgott** [comment]
Hey @mvanholsteijn 

yes both are (in that case) in region eu-central-1

**Comment by mvanholsteijn** [comment]
Did you grant SES permission to use the KMS key used for the topic? 

https://docs.aws.amazon.com/ses/latest/DeveloperGuide/configure-sns-notifications.html#configure-feedback-notifications-prerequisites

 _If you receive an error stating that an InvalidParameterValue error occurred, check the Amazon SNS topic to see if it's encrypted using AWS KMS. If it is, you have to modify the policy for the AWS KMS key._

**Comment by couchgott** [comment]
Hey, let me check again and i'll come back to you asap. :)

**Comment by mvanholsteijn** [comment]
I guess it is solved. If not, feel free to reopen this case.
