### ISSUE TITLE
Release Python 3-compatible version

### ISSUE THREAD

**Issue by bjacobel** [binxio/cfn-ses-provider#2]
Hello,

I see that the code powering this custom resource has been upgraded for Python 3 compatibility - thank you @mvanholsteijn for [this work](https://github.com/binxio/cfn-ses-provider/commit/094f1c6cf4e135d961de866162eefcf6c45f3e8d)! Are there any plans to release a version `v0.3.0` including the Python 3 compatibility to the public S3 bucket? As far as I can tell, the latest publicly available built version is `v0.2.3`, which targets Python 2.7 and thus is not compatible with the CloudFormation template present on the `master` branch.

(I discovered this issue while attempting to use v0.2.3 with the cfn template from `master`, which resulted in an error which I'll leave here to help anyone running into the same thing:)

```
Unable to import module 'ses': No module named 'Queue'
```

**Comment by mvanholsteijn** [comment]
Oops. Sorry about that. Deployed v0.3.0 with Python3 support.
