### ISSUE TITLE
InvalidCharacterString

### ISSUE THREAD

**Issue by victormesas** [binxio/cfn-ses-provider#23]
Hi!

using `!GetAtt 'MailFromDomain.RecordSets'`  I'm getting the next error on CloudFormation console:

``` [Invalid Resource Record: 'FATAL problem: InvalidCharacterString (Value should be enclosed in quotation marks) encountered with 'v=spf1 include:amazonses.com ~all'']```

Thank you!

**Comment by mvanholsteijn** [comment]
Hi Victor,  which version of the provider are you using? It was resolved in version 0.8.2

**Comment by vmesas-RatedPower** [comment]
Hi Mark, 

I'm using `cfn-ses-provider-0.8.2.zip` lambda.

Thank you!

**Comment by victormesas** [comment]
Hi Mark,

I'm using `cfn-ses-provider-0.8.2.zip lambda`.

Thank you!

**Comment by mvanholsteijn** [comment]
I implemented the fix in 0.8.3. Please let me know if it works for you,
